import { Battle, toMinutes } from "./types";

// ─────────────────────────────────────────────────────────
// תוכן אמיתי — קרבות מוצב נחל עוז, 7 באוקטובר 2023.
// יובא מאתר "מפת קרב" (Lovable / Supabase) — גדוד 13, חטיבת גולני וצוות הקרב הגדודי.
// תמונות הלוחמים מאוחסנות ב-Supabase Storage הציבורי של אותו פרויקט.
// ─────────────────────────────────────────────────────────

function build(b: Omit<Battle, "startMinute" | "endMinute">): Battle {
  return {
    ...b,
    // Marker reveals at the engagement time (the replay window can still open
    // earlier — that's handled separately in MapExperience).
    startMinute: toMinutes(b.time),
    endMinute: toMinutes(b.timeline[b.timeline.length - 1]?.time ?? b.time),
  };
}

export const BATTLES: Battle[] = [
  build({
    id: "nahal-oz-hamal",
    slug: "nahal-oz-hamal",
    title: "קרב חמ\"ל נחל עוז",
    kind: "battle",
    date: "2023-10-07",
    time: "07:30",
    coordinates: [34.500837924956, 31.4795462059209],
    locationName: "מוצב נחל עוז",
    unit: "גדוד 13, חטיבת גולני",
    summary: "קרב בלימה והגנה על חמ\"ל התצפיות במוצב נחל עוז",
    description: "בוקר השבת של ה-7 באוקטובר הפך את חמ\"ל התצפיות בנחל עוז לזירת קרב של גבורה עילאית ותנאים בלתי אפשריים. בעוד המחנה מוצף במאות מחבלים, התייצבו תצפיתניות, קציני מטה ולוחמים בקו ההגנה האחרון, נחושים להגן על \"העיניים של המדינה\" ועל חבריהם ליחידה.\nתחת אש כבדה, יצרו קציני המטה של גדוד 13 עמדת בלימה בפתח החמ\"ל, בעוד הסמב\"ציות פועלות תחת לחץ עצום להעברת תמונת מצב לחטיבה. אל הכוח הצטרפו סרן יוחאי דוכן וסרן נמרוד אלירז, יחד עם הגשש הבכיר רס\"ב איברהים ח'רובה והלוחם סמ\"ר איתי אברהם רון, לאחר שלחמו בחירוף נפש ברחבי המחנה. בנחיתות מספרית מובהקת ובנשק קל בלבד, ניהל הכוח קרב בלימה עיקש שארך שעות, כשהם הודפים גל אחר גל של מחבלים המצוידים בטילי נ\"ט ומטענים.\nבשעה 07:48 נדמו מכשירי הקשר, אך הרוח לא נשברה. סרן עידן בלוי, קצין הקשר הגדודי, המשיך לכוון כוחות מהאוויר ומהיבשה עד לרגעיו האחרונים. כשהתחמושת החלה לאזול והאויב קרא להם להיכנע, ענו הלוחמים בסירוב מוחלט. ברגע של תושייה עילאית וקרב פנים אל פנים, השתלטו הלוחמים בידיים חשופות על מחבל שניסה לפרוץ פנימה ונטרלו אותו באמצעות סכין.\nכשהבינו המחבלים כי לא יוכלו להכניע את הכוח בלחימה, השליכו לתוך החמ\"ל רימוני בערה שפלטו גזים רעילים והציתו אש תופת. בתוך חשיכה מוחלטת ועשן סמיך וחונק, סייעו הלוחמים והחיילות איש לרעהו, מגששים באפילה בניסיון נואש להציל חיים. שבעה ניצולים הצליחו לחלץ את עצמם דרך חלון השירותים הצר, בעוד חבריהם נותרים מאחור, נאבקים עד נשימתם האחרונה.\nבקרב זה נפלו גיבורי וגיבורות החמ\"ל:\nסגן יוחאי דוכן ז\"ל \nסרן עידן בלוי ז\"ל \nסרן שיר אילת ז\"ל \nרס\"ב איברהים ח'רובה ז\"ל \nסמ\"ר איתי אברהם רון ז\"ל \nסמ\"ר דניאל ראשד ז\"ל \nסמל אושר ברזילי ז\"ל \nסמ\"ר שיראל חיים-פור ז\"ל \nסמ\"ר ים גלס ז\"ל \nסמל יעל לייבושור ז\"ל \nרב\"ט מיה ויאלובו פולו ז\"ל \nסמל רוני אשל ז\"ל \nסמל שירה שוחט ז\"ל \nסמ\"ר עדי לנדמן ז\"ל \nסמל שיראל מור ז\"ל\n\nבמסירותם ובחוסנם, עמדו מגיני החמ\"ל כחומה בצורה מול אויב אכזר. הם לחמו יחד – קצינים, לוחמים ותצפיתניות – וכתבו בדם ובאש פרק של רעות וגבורה שייחרט לעד בתולדות ישראל. יהי זכרם ברוך.",
    media: [
    ],
    timeline: [
      { id: "nahal-oz-hamal-t0", time: "06:29", endTime: "07:30", title: "צבע אדום בכלל רחבי הגזרה, איוש מוגבר בחמ\"ל" },
      { id: "nahal-oz-hamal-t1", time: "07:30", endTime: "07:48", title: "ניסיונות מחבלים לחדור לחמ\"ל, לחימה עיקשת בכניסה." },
      { id: "nahal-oz-hamal-t2", time: "07:48", endTime: "11:00", title: "נופלת התקשורת בחמ\"ל" },
      { id: "nahal-oz-hamal-t3", time: "11:00", endTime: "11:30", title: "נופל החשמל בחמ\"ל" },
      { id: "nahal-oz-hamal-t4", time: "11:30", endTime: "12:00", title: "התחמושת אוזלת, הלוחמים החלו בלחימה בידיים חשופות כנגד המחבלים." },
      { id: "nahal-oz-hamal-t5", time: "12:00", endTime: "14:00", title: "המחבלים החלו לשרוף את החמ\"ל" },
      { id: "nahal-oz-hamal-t6", time: "14:00", endTime: "14:05", title: "החל מבצע חילוץ בפיקוד קציני חטיבת גולני, שבסופו חולצו שבעה חיילים מהחמ\"ל." },
    ],
    fallen: [
      {
        id: "7b8ab1e7",
        fullName: "עידן בלוי",
        rank: "סרן",
        age: 21,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/7b8ab1e7.jpg",
        hometown: "ראשון לציון",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "c2efb952",
        fullName: "שיר אילת",
        rank: "סרן",
        age: 20,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/c2efb952.jpg",
        hometown: "כפר שמואל",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
      {
        id: "23bae5e7",
        fullName: "יוחאי דוכן",
        rank: "סגן",
        age: 26,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/23bae5e7.jpg",
        hometown: "קריית ארבע",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "e218d50b",
        fullName: "איברהים ח'רובה",
        rank: "רס\"ב",
        age: 39,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/e218d50b.jpeg",
        hometown: "מע'אר",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
      {
        id: "5158bc9a",
        fullName: "איתי אברהם רון",
        rank: "סמ\"ר",
        age: 20,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/5158bc9a.jpg",
        hometown: "נס ציונה",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "e8147ff6",
        fullName: "דניאל ראשד",
        rank: "סמ\"ר",
        age: 19,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/e8147ff6.jpg",
        hometown: "שפרעם",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "9f85239e",
        fullName: "אושר שמחה ברזילי",
        rank: "סמל",
        age: 19,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/9f85239e.jpg",
        hometown: "מזכרת בתיה",
        memorial: "חטיבה צפונית",
        affiliation: "combat_team",
      },
      {
        id: "34309c7d",
        fullName: "שיראל חיים פור",
        rank: "סמ\"ר",
        age: 20,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/34309c7d.jpg",
        hometown: "ראשון לציון",
        memorial: "חטיבה צפונית",
        affiliation: "combat_team",
      },
      {
        id: "e47bf80c",
        fullName: "ים גלס",
        rank: "סמ\"ר",
        age: 20,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/e47bf80c.jpg",
        hometown: "מודיעין",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
      {
        id: "1f3c92fe",
        fullName: "יעל לייבושור",
        rank: "סמל",
        age: 20,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/1f3c92fe.jpg",
        hometown: "ירושלים",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
      {
        id: "5f5bd432",
        fullName: "מיה ויאלובו פולו",
        rank: "רב\"ט",
        age: 19,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/5f5bd432.jpg",
        hometown: "תל אביב",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
      {
        id: "1f5d755f",
        fullName: "רוני אשל",
        rank: "סמל",
        age: 19,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/1f5d755f.jpg",
        hometown: "צור יצחק",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
      {
        id: "a6135e15",
        fullName: "שירה שוחט",
        rank: "סמל",
        age: 19,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/a6135e15.jpg",
        hometown: "שריגים",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
      {
        id: "8dc7fb10",
        fullName: "עדי לנדמן",
        rank: "סמ\"ר",
        age: 19,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/8dc7fb10.jpg",
        hometown: "יקנעם עילית",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
      {
        id: "8afb3562",
        fullName: "שיראל מור",
        rank: "סמל",
        age: 19,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/8afb3562.jpg",
        hometown: "רעננה",
        memorial: "מערך הגנת הגבולות",
        affiliation: "combat_team",
      },
    ],
  }),
  build({
    id: "nahal-oz-assault",
    slug: "nahal-oz-assault",
    title: "ניסיון כיבוש המוצב",
    kind: "rescue",
    date: "2023-10-07",
    time: "08:20",
    coordinates: [34.5023344648505, 31.4785264578427],
    locationName: "מוצב נחל עוז",
    unit: "פלוגה ב', גדוד 13, חטיבת גולני",
    summary: "ניסיון כיבוש המוצב בחזרה על ידי חפ\"ק מ\"פ ב'",
    description: "בוקר השבת של ה-7 באוקטובר תפס את רס\"ן שילה הר-אבן, מפקד פלוגה ב' (\"גרנט\"), בעיצומה של היערכות לתרגיל כוננות בגזרת נחל עוז. בשעה 06:30, כשהשמיים התמלאו ב\"גשם סגול\", המציאות השתנתה באחת. בקור רוח האופייני לו, חדל שילה את התרגיל והכריז בקשר את המשפט שסימן את תחילתה של המערכה: \"זה לא תרגיל\".\nתחת אש כבדה ודיווחים על פריצות רבות בגדר, החל שילה לנהל קרב הגנה עיקש. הוא פיקד על \"צק\"ם נזמית\", שכלל נמ\"ר וטנק, והוביל אותם אל קו המגע. למרות פגיעות נ\"ט בכליו ותקלות מכאניות מורכבות שהגבילו את כושר התנועה, שילה לא נסוג. כאשר הבין כי סגן מפקד הגדוד נפצע, לקח על עצמו את הפיקוד על הגזרה כולה. \"אני לוקח פיקוד על האירוע\", הודיע בקשר, בעודו מנווט את כוחות הטנקים להגנה על קיבוץ כפר עזה \"בכל מחיר\".\nבמהלך הלחימה בתוך מחנה נחל עוז, תחת מטר של אש ומטענים, נפצע שילה בידו. למרות הפציעה, הוא חבש את עצמו בשטח, סירב להתפנות והמשיך לחתור למגע. בשעה 08:15, כשנודע לו על מחבלים שחדרו לבסיס והסכנה לחיי החיילים והתצפיתניות בחמ\"ל גוברת, קיבל שילה החלטה פיקודית עילאית: מכיוון שדלת הנמ\"ר נתקעה כתוצאה מפגיעה, הוא ולוחמיו יפרקו מהכלי וייכנסו לטיהור המחנה רגלית.\nבשורות הראשונות, בראש הכוח, הסתער שילה אל תוך המחנה. במשימה שהוגדרה \"להגן על הבית ולחסל כל אויב\", נתקל הכוח במארב מחבלים סמוך לשער הבסיס. בקרב פנים אל פנים, תוך גילוי גבורה יוצאת דופן ודבקות במשימה עד טיפת הדם האחרונה, נפלו שילה ולוחמיו.\nבקרב זה נפלו גיבורי פלוגה ב':\nרס\"ן שילה הר-אבן ז\"ל\nסמ\"ר יעד בן-יעקב ז\"ל\nסמ\"ר רועי ברקת ז\"ל\nסמ\"ר ישי פיטוסי ז\"ל\nסמ\"ר דביר זכאי ז\"ל\nסמ\"ר דור ירחי ז\"ל\nבמעשיהם ובפיקודם, בלמו לוחמי \"גרנט\" בגופם את התקדמות האויב, הצילו חיים רבים וכתבו בדם פרק מפואר של גבורה ומנהיגות בתולדות מדינת ישראל. יהי זכרם ברוך.",
    media: [
      { id: "26eeaa99", kind: "image", url: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/media/26eeaa99.jpg", caption: "" },
      { id: "3f105717", kind: "audio", url: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/media/3f105717.mp3", caption: "" },
    ],
    timeline: [
      {
        id: "nahal-oz-assault-t0",
        time: "08:20",
        endTime: "08:26",
        title: "כוח הלוחמים בפיקוד שילה הר אבן יצא להתקפה",
        // נתיב המחשה בלבד — להחלפה בנתונים מאומתים. הכוח נע מנקודת ההיערכות
        // לעבר הש.ג והבטונדות בכניסה למוצב.
        path: [
          { time: "08:20", coordinates: [34.5006, 31.4778] },
          { time: "08:23", coordinates: [34.5018, 31.4783] },
          { time: "08:26", coordinates: [34.50255, 31.47875] },
        ],
      },
      { id: "nahal-oz-assault-t1", time: "08:21", endTime: "08:22", title: "הכוח נמצא סמוך ל-ש.ג במרחב הבטונדות, הכוח מותקל, שילה מדווח על פצוע בכוח" },
      { id: "nahal-oz-assault-t2", time: "08:22", endTime: "08:22", title: "שילה מדווח: \"הותקלנו מלפנים. במספר מחבלים לא ידוע, לשכב מאחורי מחסות\". " },
      { id: "nahal-oz-assault-t3", time: "08:22", endTime: "08:26", title: "ניהול לחימה עם מחבלים רבים באזור הבטונדות בכניסה למוצב." },
      { id: "nahal-oz-assault-t4", time: "08:26", endTime: "08:26", title: "כלל הכוח הרגלי נופל." },
    ],
    fallen: [
      {
        id: "05b2ca38",
        fullName: "שילה הר אבן",
        rank: "רס\"ן",
        age: 25,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/05b2ca38.jpg",
        hometown: "ירושלים",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "24c2f70e",
        fullName: "יעד בן יעקב",
        rank: "סמ\"ר",
        age: 20,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/24c2f70e.jpg",
        hometown: "פתח תקווה",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "bb0a4a4e",
        fullName: "רועי ברקת",
        rank: "סמ\"ר",
        age: 20,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/bb0a4a4e.jpg",
        hometown: "תל אביב",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "ef83ed72",
        fullName: "ישי פיטוסי",
        rank: "סמ\"ר",
        age: 21,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/ef83ed72.jpg",
        hometown: "טלמון",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "7b963a4d",
        fullName: "דביר זכאי",
        rank: "סמ\"ר",
        age: 21,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/7b963a4d.jpg",
        hometown: "טבריה",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
      {
        id: "c97461ba",
        fullName: "דור ירחי",
        rank: "סמ\"ר",
        age: 21,
        photo: "https://szejkimsbjvdamittwlf.supabase.co/storage/v1/object/public/battle-media/fallen/c97461ba.jpg",
        hometown: "ראשון לציון",
        memorial: "גדוד 13, חטיבת גולני",
        affiliation: "battalion_13",
      },
    ],
  }),
];

export function getBattleBySlug(slug: string) {
  return BATTLES.find((b) => b.slug === slug);
}

export function allFallen() {
  return BATTLES.flatMap((b) =>
    b.fallen.map((s) => ({ ...s, battle: b.title, battleSlug: b.slug })),
  );
}
